name: update-letterbox-rss
on:
  workflow_dispatch:
    inputs:
      reason:
        description: Reason for running
        required: false
        default: Manual run
  schedule:
    - cron: 0 0 * * 6

permissions:
  contents: write

jobs:
  update_script_run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: bash update-feed.sh
      - run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add assets/letterboxdfeed.xml
          git commit -m "chore (letterboxd): update letterboxd rss feed" || true
          git push
